# Generated by Django 6.0.6 on 2026-06-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first (left to right).')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('lead', 'Lead — big top story'), ('section', 'Section column')], default='section', max_length=10)),
                ('kicker', models.CharField(blank=True, help_text='Small label above the headline, e.g. MARKETS.', max_length=60)),
                ('headline', models.CharField(max_length=200)),
                ('bullets', models.TextField(help_text='One bullet per line. Two or three short lines skim best.')),
                ('secs', models.PositiveIntegerField(default=20, help_text='Feeds the read meter.', verbose_name='Scan time (seconds)')),
                ('breaking', models.BooleanField(default=False, help_text="Shows the pulsing 'Breaking' marker.")),
                ('published', models.BooleanField(default=True, help_text='Uncheck to hide from the page without deleting.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within the placement/section.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, help_text='Required for section stories; leave blank for lead stories.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='news.section')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['order', '-created'],
            },
        ),
    ]
