# Generated by Django 6.0.6 on 2026-06-15 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_seed_edition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['order', '-created'], 'permissions': [('edit_any_story', 'Can edit stories authored by others'), ('lock_story', 'Can lock or unlock a story for editing')], 'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Who wrote this. Set automatically to the creator if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='locked',
            field=models.BooleanField(default=False, help_text='When locked, the author can no longer edit. Only Editors and Admins can lock or unlock.'),
        ),
    ]
